settings:
  interval: 5
  log_path: /var/log/nginx/access.log

clickhouse:
  db: start
  table: events
  host: 172.17.0.1
  port: 8123
  credentials:
    user: default
    password:
  columns:
    - name: environment
      key: arg_environment
      type: string
    - name: event_producer
      key: arg_event_producer
      type: string
    - name: screen_type
      key: arg_screen_type
      type: string
    - name: screen_attributes_id
      key: arg_screen_attributes_id
      type: string
    - name: screen_attributes_num
      key: arg_screen_attributes_num
      type: int
    - name: referer_screen_type
      key: arg_referer_screen_type
      type: string
    - name: referer_screen_attributes_id
      key: arg_referer_screen_attributes_id
      type: string
    - name: referer_screen_attributes_num
      key: arg_referer_screen_attributes_num
      type: int
    - name: block_type
      key: arg_block_type
      type: string
    - name: block_attributes_id
      key: arg_block_attributes_id
      type: string
    - name: block_attributes_index
      key: arg_block_attributes_index
      type: int
    - name: block_attributes_tag
      key: arg_block_attributes_tag
      type: int
    - name: element_type
      key: arg_element_type
      type: string
    - name: element_attributes_id
      key: arg_element_attributes_id
      type: string
    - name: element_attributes_index
      key: arg_element_attributes_index
      type: int
    - name: element_attributes_tag
      key: arg_element_attributes_tag
      type: int
    - name: action_id
      key: arg_action_id
      type: string
    - name: action_attributes_str
      key: arg_action_attributes_str
      type: string
    - name: action_attributes_num
      key: arg_action_attributes_num
      type: int
    - name: profile_uid
      key: arg_profile_uid
      type: string
    - name: account_id
      key: arg_account_id
      type: string
    - name: account_type
      key: arg_account_type
      type: string
    - name: profile_for_child
      key: arg_profile_for_child
      type: int
    - name: traffic_source
      key: arg_traffic_source
      type: string
    - name: content_uid
      key: arg_content_uid
      type: string
    - name: referer_content_uid
      key: arg_referer_content_uid
      type: string
    - name: device_uid
      key: arg_device_uid
      type: string
    - name: device_type
      key: arg_device_type
      type: string
    - name: device_model
      key: arg_device_model
      type: string
    - name: device_vendor
      key: arg_device_vendor
      type: string
    - name: platform_id
      key: arg_platform_id
      type: string
    - name: platform_api_key
      key: arg_apikey
      type: string
    - name: user_agent
      key: http_user_agent
      type: string
    - name: user_screen_width
      key: arg_user_screen_width
      type: int
    - name: user_screen_height
      key: arg_user_screen_height
      type: int
    - name: request_country
      key: http_country_code
      type: string
    - name: request_ip
      key: remote_addr
      type: string
    - name: request_referer
      key: http_referer
      type: string
    - name: client_version
      key: arg_client_version
      type: int
    - name: server_version
      key: arg_server_version
      type: int
    - name: time_local
      key: time_local
      type: time
    - name: event_time
      key: arg_event_time
      type: time

nginx:
  log_type: events
  log_format: $arg_environment|$arg_event_producer|$arg_screen_type|$arg_screen_attributes_id|$arg_screen_attributes_num|$arg_referer_screen_type|$arg_referer_screen_attributes_id|$arg_referer_screen_attributes_num|$arg_block_type|$arg_block_attributes_id|$arg_block_attributes_index|$arg_block_attributes_tag|$arg_element_type|$arg_element_attributes_id|$arg_element_attributes_index|$arg_element_attributes_tag|$arg_action_id|$arg_action_attributes_str|$arg_action_attributes_num|$arg_profile_uid|$arg_account_id|$arg_account_type|$arg_profile_for_child|$arg_traffic_source|$arg_content_uid|$arg_referer_content_uid|$arg_device_uid|$arg_device_type|$arg_device_model|$arg_device_vendor|$arg_platform_id|$arg_apikey|$http_user_agent|$arg_user_screen_width|$arg_user_screen_height|$http_country_code|$remote_addr|$http_referer|$arg_client_version|$arg_server_version|$time_local|$arg_event_time
